apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "hello-wide-world"
    spec:
      selector:
        app: "hello-wide-world"
      type: LoadBalancer
      ports:
        - name: http
          port: 8080
          targetPort: 8080
          protocol: TCP
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      labels:
        app: "hello-wide-world"
      name: "hello-wide-world"
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: "hello-wide-world"
      template:
        metadata:
          labels:
            app: "hello-wide-world"
        spec:
          containers:
            - image: "hello-wide-world"
              imagePullPolicy: "Never"
              name: "hello-wide-world"
              ports:
                - protocol: TCP
                  containerPort: 8080